export enum ENUM_ROUTES {
  HOME = '/',
  WORKSHOPS = '/workshops',
  PRODUCTS = '/products',
  CHECKOUT = '/checkout',
  CHECKOUT_CART = '/checkout/processing',
  CHECKOUT_DELIVERY = '/checkout/processing/delivery',
  CHECKOUT_PAYMENT = '/checkout/processing/payment',
  CHECKOUT_RESULT = '/checkout/result',
  CHECKOUT_SUCCESS = '/checkout/success',
  CHECKOUT_FAILED = '/checkout/failed',
  CHECKOUT_INFORMATIONS = '/checkout/processing/informations',
  CREATE_INVOICE = '/api/invoices/create',
  CREATE_ORDER = '/api/orders/create',
}
