export enum ENUM_ROUTES {
  HOME = '/',
  WORKSHOPS = '/workshops',
  ARTWORKS_CREATE = '/dashboard/artworks/create',
  ARTWORKS_DETAIL = '/dashboard/artworks',
  PRODUCTS = '/products',
  CHECKOUT = '/checkout',
  CHECKOUT_CART = '/checkout',
  CHECKOUT_DELIVERY = '/checkout/delivery',
  CHECKOUT_PAYMENT = '/checkout/payment',
  CHECKOUT_RESULT = '/payment',
  CHECKOUT_SUCCESS = '/checkout/success',
  CHECKOUT_FAILED = '/checkout/failed',
  CHECKOUT_INFORMATIONS = '/checkout/informations',
  CREATE_INVOICE_API = '/api/invoices/create',
  CREATE_INVOICE = '/dashboard/financial/invoices/create',
  INVOICE_DETAIL = '/dashboard/financial/invoices',
  CREATE_ORDER = '/api/orders/create',
  CUSTOMERS = '/dashboard/customers',
  CUSTOMERS_CREATE = '/dashboard/customers/create',
  CONTACT = '/contact',
  LEGALS = '/legals',
  GALLERY = '/gallery',
  ESTIMATES = '/dashboard/financial/estimates',
  CREATE_ESTIMATE = '/dashboard/financial/estimates/create',
  INVOICE_PDF_GENERATE = '/api/invoices/generate'
}
