export enum ENUM_COLLECTIONS {
  PROFILES = 'profiles',
  PRODUCTS = 'products',
  MEDIAS = 'medias',
  CATEGORIES = 'categories',
  TEMPLATES = 'templates',
  WORKSHOPS = 'workshops',
  LOCATIONS = 'locations',
  SUBSCRIPTIONS = 'subscriptions',
  INVOICES = 'invoices',
  ORDERS = 'orders',
  BOOKINGS = 'bookings',
  INVOICESIDS = 'invoicesIds',
  CUSTOMERS = 'customers',
  TESTIMONIALS = 'testimonials',
  ARTWORKS = 'artworks',
  ESTIMATES = 'estimates',
  VENDORS = 'vendors',
}
